# Generated by Django 5.2.10 on 2026-01-22 10:01

import organizations.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0004_auto_20230727_2054'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalorganization',
            name='reward_currency_full_name',
            field=models.CharField(default='Points', help_text='Full name of the reward currency (e.g., "Learning Points", "Achievement Coins", "Skill Crowns", "Progress Stars").', max_length=100, verbose_name='Reward Currency Full Name'),
        ),
        migrations.AddField(
            model_name='historicalorganization',
            name='reward_currency_short_name',
            field=models.CharField(default='points', help_text='Short identifier for the reward currency (e.g., points, coins, stars, crowns). Only Latin letters, digits, underscore (_), and hyphen (-) are allowed. Will be used in APIs and internal references.', max_length=50, validators=[organizations.models.validate_currency_short_name], verbose_name='Reward Currency Short Name'),
        ),
        migrations.AddField(
            model_name='organization',
            name='reward_currency_full_name',
            field=models.CharField(default='Points', help_text='Full name of the reward currency (e.g., "Learning Points", "Achievement Coins", "Skill Crowns", "Progress Stars").', max_length=100, verbose_name='Reward Currency Full Name'),
        ),
        migrations.AddField(
            model_name='organization',
            name='reward_currency_short_name',
            field=models.CharField(default='points', help_text='Short identifier for the reward currency (e.g., points, coins, stars, crowns). Only Latin letters, digits, underscore (_), and hyphen (-) are allowed. Will be used in APIs and internal references.', max_length=50, validators=[organizations.models.validate_currency_short_name], verbose_name='Reward Currency Short Name'),
        ),
    ]
